### ISSUE TITLE
REQ - Have bot include identifier with reports.

### ISSUE THREAD

**Issue by Munkenmo** [jack-webb/reddit-submision-limiter#6]
The bot is picking up a lot of instances where users have deleted their prior  posts / comments within them making it hard to differentiate from a false positive.

At the moment once the bot detects 3  posts, 

- If a user hasn't deleted any posts; all 3 will show up in the mod queue
- If a user has deleted prior posts, only ones that aren't deleted appear in the mod queue, (appearing to be a false positive).

I'd like to look at the previous posts to see if a user has simply deleted and corrected  a post with a mistake (which I'd let slide) or if they're deliberately circumventing our rules. In order to do this I'm hoping the bot can do one of the following :

- When making a report, include the unique identifier from the previously posted URL's. 
- Add a Spam Watch usernote containing the unique identifier.

**Comment by jack-webb** [comment]
Post IDs and the total post count are now given in the report message. Subsequent extra posts above the threshold(s) will include the later post IDs, but earlier reports will not be updated (reddit limitation afaict).

Toolbox integration seems pretty tricky to do nicely/properly, so that's not on the cards atm. I'm open to PRs, but don't have any plans to implement it currently.
